# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: zective
google_analytics: 
title: zective.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: zective.github.io

avatar: https://avatars0.githubusercontent.com/u/3415163?s=120

description: Oooops
author:
  name: Zective
  email: zective@gmail.com
  github: zective
  twitter: zective
  pinterest: 
  linkedin: zective
  bio: With python
  email_md5: 70751c629895308bc167790513c06b1d

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://avatars0.githubusercontent.com/u/3415163?s=120

BASE_PATH:

gems:
  - jekyll-paginate
